name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Lint with Checkstyle
      run: mvn checkstyle:run
      
    - name: Run unit tests with Junit
      run: mvn test