name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint with Checkstyle
      run: mvn checkstyle:check
      
    - name: Run unit tests with Junit
      run: mvn test